import 'package:get/get.dart';

class Langues extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        
        'fr_FR': {
          'slogan': 'Votre site de réservation N°1 en Afrique',
          'commencer': 'Commencer',
          'inscription': 'Inscrivez-vous',
          'inscription_message': 'Là où vous rêvez d\'aller, nous vous y amenons.',
          'nom': 'Nom',
          'e-mail': 'E-mail',
          'numero': 'Numéro(+225...)',
          'continuer': 'Continuer',
          'compte_existant': 'J\'ai déjà un compte',
          'champ_vide': 'Les champs ne doivent pas être vides.',
          'alerte_nom': 'Entrez un nom uniquement avec des lettres.',
          'alerte_e-mail': 'Entrez une adresse E-mail valide.',
          'alerte_extension': 'Extension de domaine invalide.',
          'alerte_domaine': 'Domaine de messagerie invalide.',
          'alerte_numero': 'Entrez un numéro valide.',
          'connexion': 'Connectez-vous',
          'connexion_message': 'Nous sommes ravis de vous revoir.',
          'numero_existant': 'Numéro',
          'numero_enregistré': 'Ce numéro de téléphone est déjà utilisé.',
          'erreur_inscription': 'Erreur lors de l\'inscription. Veuillez réessayer.',
          'connexion_numero': 'Veuillez entrer un numéro de téléphone.',
          'message': 'Le numéro de téléphone n\'est pas enregistré.',
        },
        'en_US': {
          'slogan': 'Your No. 1 reservation site in Africa',
          'commencer': 'Start',
          'inscription': 'Register',
          'inscription_message': 'Where you dream of going, we will take you there.',
          'nom': 'Name',
          'e-mail': 'Email',
          'numero': 'Number(+225...)',
          'continuer': 'Continue',
          'compte_existant': 'I already have an account',
          'champ_vide': 'Fields must not be empty.',
          'alerte_nom': 'Enter a name with letters only.',
          'alerte_e-mail': 'Enter a valid Email address.',
          'alerte_extension': 'Invalid domain extension.',
          'alerte_domaine': 'Invalid Email domain.',
          'alerte_numero': 'Enter a valid number.',
          'connexion': 'Log in',
          'connexion_message': 'We are delighted to see you again.',
          'numero_existant': 'Number',
          'numero_enregistré' : 'This phone number is already in use.',
          'erreur_inscription': 'Error during registration. Try again.',
          'connexion_numero': 'Please enter a phone number.',
          'message': 'The phone number is not saved.',
        },
        'es_ES': {
          'slogan': 'Su sitio de reservas número uno en África',
          'commencer': 'Comenzar',
          'inscription': 'Registro',
          'inscription_message': 'Donde sueñas ir, nosotros te llevaremos allí.',
          'nom': 'Apellido',
          'e-mail': 'Correo electrónico',
          'numero': 'Número(+225...)',
          'continuer': 'Seguir',
          'compte_existant': 'Ya tengo una cuenta',
          'champ_vide': 'Los campos no deben estar vacíos.',
          'alerte_nom': 'Ingrese un nombre solo con letras.',
          'alerte_e-mail': 'Introduzca un correo electrónico válido.',
          'alerte_extension': 'Extensión de dominio no válida.',
          'alerte_domaine': 'Dominio de correo electrónico no válido.',
          'alerte_numero': 'Introduzca un número válido.',
          'connexion': 'Acceso',
          'connexion_message': 'Estamos encantados de verte de nuevo.',
          'numero_existant': 'Número',
          'numero_enregistré' : 'Este número de teléfono ya está en uso.',
          'erreur_inscription': 'Error durante el registro. Intentar otra vez.',
          'connexion_numero': 'Por favor, ingrese un número de teléfono.',
          'message': 'El número de teléfono no se guarda.',
        }
      };
}